### ISSUE TITLE
Circular dependency in DI detected for ApplicationRef after ngx-smart-modal and angular upgrade

### ISSUE THREAD

**Issue by Bierat1337** [maximelafarie/ngx-smart-modal#387]
Hi,

I upgraded Angular 15 to 16 and ngx-smart-modal from 7.1.1 to 14.0.3.
After the upgrade I am getting the following error:

Error: NG0200: Circular dependency in DI detected for ApplicationRef. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.mjs:228:11)
    at R3Injector.hydrate (core.mjs:9448:13)
    at R3Injector.get (core.mjs:9323:33)
    at injectInjectorOnly (core.mjs:842:40)
    at Module.ɵɵinject (core.mjs:848:60)
    at Object.NgxSmartModalService_Factory [as factory] (ngx-smart-modal.mjs:284:104)
    at core.mjs:9454:43
    at runInInjectorProfilerContext (core.mjs:798:9)
    at R3Injector.hydrate (core.mjs:9453:17)
    at R3Injector.get (core.mjs:9323:33)

I tried to find the issue, but the circular dependency error isn't caused by any of my created components or services. It seems to be caused by the upgrade of the lib.

Do you guys have any idea how to fix this issue?

regards,
Bierat

**Comment by maximelafarie** [comment]
Hi, there,

sorry, I got married recently and have had a lot going on at the moment which (once again) has made it very difficult for me to refocus.

The problem you are experiencing may be due to the double import of `ApplicationRef` into `NgxSmartModalService`. I'm surprised more people haven't had this error. I'm going to get more fixes on board soon, just to make sure the code base is clean.

Stay tuned 🖖

**Comment by Bierat1337** [comment]
Hi,

thanks for answering to my issue. Congratulations on getting married! :).
Do you already know when you will be able to fix that issue with the ApplicationRef?

Unfortunately I still got the problem. I used ngxsmartmodal a lot in this project, so its horrible to switch to an alternative.

Regards,
Bierat

**Comment by maximelafarie** [comment]
Released as `14.1.0`. 
Thank you again for contributing!
